version: '3.8'

services:
  # 1. Banco Relacional (User, Finance, Routine)
  postgres:
    image: postgres:15-alpine
    container_name: lifedev-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lifedev-net

  # 2. Banco NoSQL (Health, Economic)
  mongodb:
    image: mongo:6.0
    container_name: lifedev-mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - lifedev-net

  # 3. Cache em Memória
  redis:
    image: redis:7-alpine
    container_name: lifedev-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - lifedev-net

  # 4. Message Broker (RabbitMQ com Painel Visual)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lifedev-rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"   # Porta por onde os microsserviços conversam
      - "${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}" # Porta do painel visual
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lifedev-net

  # 5. IAM - Autenticação e Segurança
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: lifedev-keycloak
    command: start-dev
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    networks:
      - lifedev-net

  # 6. Automação e IA (Motor de Insights)
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: lifedev-n8n
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - lifedev-net

networks:
  lifedev-net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
  n8n_data: