quarkus.http.port=8000

# Habilita o CORS
quarkus.http.cors.enabled=true

# Define a origem permitida (o endereço do seu frontend)
quarkus.http.cors.origins=http://localhost:5173

# URL do Keycloak (Realm)
quarkus.oidc.auth-server-url=http://localhost:8080/realms/life-os
quarkus.oidc.client-id=api-gateway

# Diz que as requisições para a API precisam de autenticação
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated


quarkus.http.auth.permission.public.paths=/api/user/register
quarkus.http.auth.permission.public.policy=permit

# Credenciais do Keycloak Admin Client
keycloak.admin.server-url=http://localhost:8080
keycloak.admin.realm=master
keycloak.admin.clientId=admin-cli
keycloak.admin.username=${KEYCLOAK_ADMIN:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}

# Mapeamento do REST Client "user-service" para a URL real do microsserviço
quarkus.rest-client.user-service.url=http://localhost:8001      